################################################################################
reader_1:
  sn: "001625127C5D"
  active: true

  # right
  antenna_1:
    active: true
    x: 0.145
    y: -0.08
    z: 0.995

  # left
  antenna_2:
    active: true
    x: 0.145
    y: 0.05
    z: 0.995
