local_costmap:
  global_frame: rb1_base_odom
#  global_frame: /odom_combined
  robot_base_frame: rb1_base_base_footprint
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05 #0.05
  # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.0
inflation_layer:
  inflation_radius: 0.25   

