robot_base_frame: rb2_base_footprint
laser:
  - front_laser/scan_navigation
  - rear_laser/scan_navigation
interpolator:
  angular:
    min_distance: 0.65
    max_distance: 0.8 #3
    vel_at_min_distance: 0.1
    vel_at_max_distance: 0.2 
  front:
    forward:
      min_distance: 0.8
      max_distance: 2.0 #3
      vel_at_min_distance: 0.1
      vel_at_max_distance: 1.0 
    backward:
      min_distance: 0.75
      max_distance: 1.0 #3
      vel_at_min_distance: 0.1
      vel_at_max_distance: 1.0 
  rear:
    forward: # this is forward
      min_distance: 0.75
      max_distance: 1.0
      vel_at_min_distance: 0.1
      vel_at_max_distance: 1.0 
    backward: # this is backward
      min_distance: 0.8
      max_distance: 2.0
      vel_at_min_distance: 0.1
      vel_at_max_distance: 1.0 
